---
- name: Configure application
  hosts: app
  vars:
    db_host: 10.132.0.2
  become: yes
  tasks:
  - name: Add config for DB connection
    become: no
    template:
      src: templates/db_config.j2
      dest: /home/appuser/db_config

  - name: Add unit file for Puma
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
    notify: reload puma

  - name: enable puma
    service:
      name: puma
      enabled: yes

  handlers:
  - name: reload puma
    service:
      name: puma
      state: reloaded
...
