---
- name: Configure application
  hosts: app
  become: yes
  gather_facts: no

  pre_tasks:
    - name: Bootstrap a host without python2 installed
      raw: test -e /usr/bin/python2 || (apt-get update && apt-get install -y python-minimal)
      changed_when: False

  roles:
    - app

...
